defaults:
  - _self_
  - env: pendulum
  - alg: bac
name: "default"
num_eval_trials: 3
eval_frequency: 50
env:
    teleport: False
    normalize_env: False

num_iters: ${alg.num_iters}
seed: 13
mpc: ${env.mpc}
fixed_start_obs: True
num_samples_mc: 1
num_init_data: 1
test_set_size: 1000
n_paths: 15
normalize_env: ${env.normalize_env}
n_rand_acqopt: ${alg.n_rand_acqopt}
crop_to_domain: True
teleport: ${env.teleport}
hydra:
  job:
    name: ${name}
  run:
      dir: experiments/${name}_${now:%Y-%m-%d}/${now:%H-%M-%S}
